### PR TITLE
add varuint-bitcoin

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by mafintosh** [comment]
thanks. btw glanced through your code as i was intrigued and saw this typo, https://github.com/fanatid/varuint-bitcoin/blob/master/index.js#L1

**Comment by fanatid** [comment]
haha, so much words struct, of course should be strict :)

**Comment by mafintosh** [comment]
i wish i could use structs in js as well

**Comment by mafintosh** [comment]
maybe standard can check for this? /cc @feross

**Comment by fanatid** [comment]
fixed
link on typo [`'use struct'`](https://github.com/fanatid/varuint-bitcoin/blob/d76ddbbf0960dd1c43a53a488fa570c69aa227d2/index.js#L1)

**Comment by watson** [comment]
@mafintosh pro tip (if you didn't already know): When linking to a line in a file on github, press the `y` key to make the link lock to the current commit. That way if the file changes later, the link still points to the correct line as it was when you made the link :smiley:

**Comment by fanatid** [comment]
@watson I also didn't know about `y`, thank you!

**Comment by feross** [comment]
@watson nice tip!

@mafintosh Can't make `standard` check for this easily without forcing everyone to start using `'use strict'`. This is the eslint rule: http://eslint.org/docs/rules/strict

**Pull request merged**
